### ISSUE TITLE
Clean Up Code 

### ISSUE THREAD

**Issue by meenal21** [Sammeeey/batch-square-images#1]
Perform tasks to clean up the code

**traget file:** [square.py](https://github.com/Sammeeey/batch-square-images/blob/main/square.py)

## Tasks
- [ ] Sorting the imports alphabetically in the code.
- [ ] Adding comments to the code to describe functionality
- [ ] Removing unnecessary comments/codes.

Issue had been opened following the TODO mentioned in the python script.

**Comment by Sammeeey** [comment]
Great!
Thank you for the quick contribution @meenal21 

Do you want to do (some of) these tasks?
